# Generated by Django 6.0.3 on 2026-03-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('item_icon', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=50)),
                ('item_use', models.CharField(max_length=150)),
                ('item_availability', models.CharField(max_length=250)),
                ('item_description', models.TextField()),
                ('category_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', verbose_name=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterpretationEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entities')),
                ('interpretation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.interpretations')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=100)),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_source_ref', to='api.entities')),
                ('target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_target_ref', to='api.entities')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_eID', to='api.entities')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_tID', to='api.tags')),
            ],
        ),
    ]
