# Generated by Django 6.0.3 on 2026-03-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterpretationEntities',
            new_name='InterpretationOfEntities',
        ),
        migrations.RenameModel(
            old_name='EntityTags',
            new_name='TagsOfEntities',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='tag',
        ),
    ]
