# Generated by Django 6.0.3 on 2026-03-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_interpretationentities_interpretationofentities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretations',
            name='comments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
