# Generated by Django 6.0.3 on 2026-04-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_interpretations_comments_alter_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpretationofentities',
            old_name='entity_id',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='interpretationofentities',
            old_name='interpretation_id',
            new_name='interpretation',
        ),
        migrations.RenameField(
            model_name='tagsofentities',
            old_name='entity_id',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='tagsofentities',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
