# Generated by Django 6.0.3 on 2026-05-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_entity_id_interpretationofentities_entity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpretationofentities',
            old_name='interpretation',
            new_name='interpret',
        ),
    ]
