# Generated by Django 6.0.3 on 2026-05-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_interpretation_interpretationofentities_interpret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationofentities',
            name='entity',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='api.entities'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interpretationofentities',
            name='interpret',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='api.interpretations'),
            preserve_default=False,
        ),
    ]
