# Generated by Django 6.0.2 on 2026-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='item_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='item_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='item_use',
            field=models.BooleanField(default=True),
        ),
    ]
