# Generated by Django 6.0.2 on 2026-03-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_blogpost_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='item_availability',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='item_use',
            field=models.CharField(max_length=150),
        ),
    ]
