# Generated by Django 6.0.2 on 2026-03-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpost_item_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
