# Generated by Django 6.0.2 on 2026-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogpost_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soulsborne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('item_icon', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=50)),
                ('item_use', models.CharField(max_length=150)),
                ('item_availability', models.CharField(max_length=250)),
                ('item_description', models.TextField()),
                ('category_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
